# Generated by Django 4.2.7 on 2023-11-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitinsightBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_as_member', models.IntegerField()),
                ('weigth', models.CharField(max_length=100)),
                ('days_before', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=50)),
                ('attended', models.BooleanField()),
                ('previsao_presenca', models.BooleanField()),
            ],
        ),
    ]
