# Generated by Django 4.2.7 on 2023-11-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_fitinsightbase_previsao_presenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitinsightbase',
            old_name='weigth',
            new_name='weight',
        ),
    ]
