# Generated by Django 4.2.7 on 2023-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_weigth_fitinsightbase_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitinsightbase',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
