# Generated by Django 4.2.7 on 2023-11-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fitinsightbase_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitinsightbase',
            name='presence',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
