# Generated by Django 4.2.7 on 2023-12-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_fitinsightbase_presence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComPrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_as_member', models.IntegerField()),
                ('weight', models.CharField(max_length=100)),
                ('days_before', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=50)),
                ('attended', models.BooleanField()),
            ],
        ),
    ]
